export type Player = {
  Team?: string;
  Name?: string;
  Pos?: string;
  "Off Stars"?: string | number;
  "Def Stars"?: string | number;
  Size?: string | number;
  Strength?: string | number;
  Speed?: string | number;
  Stamina?: string | number;
  Poise?: string | number;
  Accuracy?: string | number;
  "Arm-Strength"?: string | number;
  "Read Defense"?: string | number;
  Juke?: string | number;
  Vision?: string | number;
  Acceleration?: string | number;
  "Route Running"?: string | number;
  Jump?: string | number;
  Hands?: string | number;
  "Ball Security"?: string | number;
  "QB Favorite"?: string | number;
  "Run Blocking"?: string | number;
  "Pass Protect"?: string | number;
  RunStop?: string | number;
  Tackling?: string | number;
  "Run Def"?: string | number;
  "Tackle Chance"?: string | number;
  Strip?: string | number;
  PassRush?: string | number;
  "Sack Chance"?: string | number;
  "Ball Hawk"?: string | number;
  "Read QB"?: string | number;
  Coverage?: string | number;
  DefPos?: string;
  Image?: string;
  "Player Image from AI"?: string;
  translateX?: string | number;
  translateY?: string | number;
  scale?: string | number;
  jersey?: string;
  Jersey?: string;
  "Jersey Image"?: string;
};
