import type { LeagueGame, LeagueTeam } from "./types";

// TODO: Replace fallback games with the read-only Games sheet API when local Sheets credentials are unavailable.
export const mockGames: LeagueGame[] = [
  {
    GameId: 1,
    Home: "LV",
    Away: "DEN",
    HomeScore: 14,
    AwayScore: 17,
    Qtr: 3,
    Time: "5:42",
    Down: 2,
    Distance: 7,
    BallOn: 64,
    Possession: "Home",
  },
  {
    GameId: 2,
    Home: "CHI",
    Away: "GB",
    HomeScore: 24,
    AwayScore: 21,
    Qtr: "FINAL",
    Time: "0:00",
    Down: 1,
    Distance: 10,
    BallOn: 50,
    Possession: "Away",
  },
];

// TODO: Replace fallback standings with the Teams sheet through /api/teams in production-like local runs.
export const mockTeams: LeagueTeam[] = [
  {
    Abbrev: "POR",
    Team: "PORTLAND WILDFIRE",
    City: "PORTLAND",
    Nickname: "WILDFIRE",
    Logo: "https://andrew-jacobson06.github.io/public-audio/wildfire.png",
    Division: "West",
    Wins: 1,
    Losses: 1,
    Ties: 0,
    "Home W": 1,
    "Home L": 0,
    "Away W": 0,
    "Away L": 1,
    "Div W": 0,
    "Div L": 0,
    PF: 13,
    PA: 16,
    Streak: "L1",
  },
  {
    Abbrev: "CLT",
    Team: "CHARLOTTE KINGSMEN",
    City: "CHARLOTTE",
    Nickname: "KINGSMEN",
    Logo: "https://andrew-jacobson06.github.io/public-audio/kingsmen.png",
    Division: "East",
    Wins: 1,
    Losses: 1,
    Ties: 0,
    "Home W": 1,
    "Home L": 0,
    "Away W": 0,
    "Away L": 1,
    "Div W": 0,
    "Div L": 0,
    PF: 13,
    PA: 15,
    Streak: "W1",
  },
  {
    Abbrev: "ABQ",
    Team: "ALBUQUERQUE VORTEX",
    City: "ALBUQUERQUE",
    Nickname: "VORTEX",
    Logo: "https://andrew-jacobson06.github.io/public-audio/vortex.png",
    Division: "West",
    Wins: 1,
    Losses: 1,
    Ties: 0,
    "Home W": 1,
    "Home L": 0,
    "Away W": 0,
    "Away L": 1,
    "Div W": 0,
    "Div L": 0,
    PF: 24,
    PA: 22,
    Streak: "L1",
  },
];
