import type { LeagueGame, LeagueTeam } from "./types";

// TODO: Replace fallback games with the read-only Games sheet API when local Sheets credentials are unavailable.
export const mockGames: LeagueGame[] = [
  {
    GameId: 1,
    Home: "LV",
    Away: "DEN",
    HomeScore: 14,
    AwayScore: 17,
    Qtr: 3,
    Time: "5:42",
    Down: 2,
    Distance: 7,
    BallOn: 64,
    Possession: "Home",
    Week: 1,
    Date: "Sun, Sep 7",
    StartTime: "1:00 PM",
  },
  {
    GameId: 2,
    Home: "CHI",
    Away: "GB",
    HomeScore: 24,
    AwayScore: 21,
    Qtr: "FINAL",
    Time: "0:00",
    Down: 1,
    Distance: 10,
    BallOn: 50,
    Possession: "Away",
    Week: 1,
    Date: "Sun, Sep 7",
    StartTime: "4:25 PM",
  },
  { GameId: 3, Home: "MIA", Away: "BUF", HomeScore: 0, AwayScore: 0, Qtr: 1, Time: "15:00", Down: 1, Distance: 10, BallOn: 25, Possession: "Away", Week: 2, Date: "Sun, Sep 14", StartTime: "1:00 PM" },
  { GameId: 4, Home: "DAL", Away: "NYG", HomeScore: 0, AwayScore: 0, Qtr: 1, Time: "15:00", Down: 1, Distance: 10, BallOn: 25, Possession: "Away", Week: 2, Date: "Sun, Sep 14", StartTime: "8:20 PM" },
  { GameId: 5, Home: "SF", Away: "SEA", HomeScore: 0, AwayScore: 0, Qtr: 1, Time: "15:00", Down: 1, Distance: 10, BallOn: 25, Possession: "Away", Week: 3, Date: "Sun, Sep 21", StartTime: "4:05 PM" },
  { GameId: 6, Home: "KC", Away: "LAC", HomeScore: 0, AwayScore: 0, Qtr: 1, Time: "15:00", Down: 1, Distance: 10, BallOn: 25, Possession: "Away", Week: 4, Date: "Mon, Sep 29", StartTime: "8:15 PM" },
];

// TODO: Replace fallback standings with the Teams sheet through /api/teams in production-like local runs.
export const mockTeams: LeagueTeam[] = [
  {
    Team: "Denver",
    Division: "West",
    Wins: 5,
    Losses: 3,
    Ties: 0,
    PF: 188,
    PA: 144,
    Streak: "W2",
  },
  {
    Team: "Las Vegas",
    Division: "West",
    Wins: 2,
    Losses: 6,
    Ties: 0,
    PF: 132,
    PA: 201,
    Streak: "L1",
  },
  {
    Team: "Green Bay",
    Division: "North",
    Wins: 4,
    Losses: 4,
    Ties: 0,
    PF: 171,
    PA: 170,
    Streak: "L1",
  },
];
