export type LeagueTab = "news" | "scores" | "schedules" | "standings" | "stats" | "draft";
export type GameTab = "gamecast" | "playbyplay" | "boxscore" | "teamstats";

export type LeagueGame = {
  GameId: string | number;
  Home: string;
  Away: string;
  HomeScore: string | number;
  AwayScore: string | number;
  Qtr: string | number;
  Time: string | number;
  Down: string | number;
  Distance: string | number;
  BallOn: string | number;
  Possession: "Home" | "Away" | string;
  /** Team that received the opening kickoff; the other team receives in Q3. */
  OpeningPossession?: "Home" | "Away" | string;
  Week?: string | number;
  "Kickoff Time"?: string;
  Date?: string;
  Kickoff?: string;
  Network?: string;
  Weather?: string;
  Location?: string;
  Stadium?: string;
  Venue?: string;
  HomeLogo?: string;
  AwayLogo?: string;
  HomeName?: string;
  AwayName?: string;
  "Home Record"?: string;
  "Away Record"?: string;
};

export type LeagueTeam = Record<string, string | number | undefined> & {
  ID?: string | number;
  Team?: string;
  Name?: string;
  City?: string;
  Nickname?: string;
  Division?: string;
  Logo?: string;
  Abbrev?: string;
  Location?: string;
  "Home Jersey Crop"?: string;
  "Away Jersey Crop"?: string;
  "Home Uniform"?: string;
  "Away Uniform"?: string;
  "Primary Color"?: string;
  "secondary color"?: string;
  "third color"?: string;
  CapSpace?: string | number;
  Wins?: string | number;
  Losses?: string | number;
  Ties?: string | number;
  PF?: string | number;
  PA?: string | number;
  DIFF?: string | number;
  STRK?: string;
  Streak?: string;
  "Home W"?: string | number;
  "Home L"?: string | number;
  "Away W"?: string | number;
  "Away L"?: string | number;
  "Div W"?: string | number;
  "Div L"?: string | number;
};
